### ISSUE TITLE
"Error: stdout maxBuffer exceeded" when exporting big repositories

### ISSUE THREAD

**Issue by eglinetwork** [francisbyrne/grunt-svn-export#1]
The grunt task svn-export runs into an Error:

```
Running "svn_export:dev" (svn_export) task
Exporting from http://path.to/repo
>> #svn export http://path.to/repo target
>> Error: stdout maxBuffer exceeded.
```

The task configuration is:

```
svn_export: {
  dev: {
    options: {
      repository: 'http://path.to/repo',
      output: 'target'
    }
  }
}
```

Is it possible to increase nodejs maxBuffer for a specific gruntjs task?

**Comment by eglinetwork** [comment]
Could you please publish the latest version to the npm repository. Than this bug could be closed. Many thanks.

**Comment by eglinetwork** [comment]
Could you please publish the latest version to the npm repository. Than this bug could be closed. Many thanks.

**Comment by francisbyrne** [comment]
@eglinetwork Done. Sorry for the (lengthy) delay!
