### ISSUE TITLE
Npm install don't work - File not found

### ISSUE THREAD

**Issue by mdunisch** [francisbyrne/grunt-svn-export#3]
When using _npm install grunt-svn-export --save-dev_

I get:

``` npm
ERR! fetch failed https://registry.npmjs.org/grunt-svn-export/-/grunt-svn-export0.1.4.tgz
```

**Comment by francisbyrne** [comment]
@mdunisch Hi, thanks for raising this. I can't seem to reproduce this, `npm install grunt-svn-export --save-dev` works fine on my local machine. However, I did notice that if I try and access the `https://registry.npmjs.org/grunt-svn-export/-/grunt-svn-export0.1.4.tgz` link directly, it gives `{"error":"not_found","reason":"Document is missing attachment"}`

I recently patched this package so I might see if I can redeploy.

**Comment by mdunisch** [comment]
have you tried `npm cache clear`?
Maybe its cached on our local machine

**Comment by francisbyrne** [comment]
@mdunisch Thanks for that. Something weird was going on with my npm so I installed a fresh copy and published a new version. Try it now (and feel free to close this if it works!).

**Comment by mdunisch** [comment]
It works - thank you!
